const PathConstants = {
  HOME: "/user",
  FORGOTPASSWORD: "/forgot-password",
  ADMIN: "/admin",
  MANAGEUSERS: "/admin/manage-users",
  MANAGECOLLEGES: "/admin/manage-colleges",
  MANAGETESTS: "/admin/manage-tests",

  SCIENCE: "/user/science",
  MEDICINE: "/user/science/medicine",
  ENGINEERING: "/user/science/engineering",
  BIOTECHNOLOGY: "/user/science/biotech",
  EVS: "/user/science/evs",
  RESEARCH: "/user/science/research",

  COMMERCE: "/user/commerce",
  ACCOUNTING: "/user/commerce/accounting",
  FINANCE: "/user/commerce/finance",
  MARKETING: "/user/commerce/marketing",
  BUSINESS: "/user/commerce/business",
  ECONOMICS: "/user/commerce/economics",

  TECHNOLOGY: "/user/technology",
  SOFTWAREDEV: "/user/technology/software_devolpoment",
  CYBERSECURITY: "/user/technology/cyber_security",
  DATASCIENCE: "/user/technology/data_science",
  AI: "/user/technology/artificial_intelligence",
  CLOUD: "/user/technology/cloud_computing",

  ARTS: "/user/arts",
  FINEARTS: "/user/arts/fine_arts",
  LITERATURE: "/user/arts/literature",
  PERFORMINGARTS: "/user/arts/performing-arts",
  HISTORYANDCULTURE: "/user/arts/history_and_culture",
  JOURNALISM: "/user/arts/journalism",

  DESIGN: "/user/design",
  GRAPHICDESIGN: "/user/design/graphic_design",
  FASHION: "/user/design/fashion_design",
  INTERIORDESIGN: "/user/design/interior_design",
  INDUSTRYDESIGN: "/user/design/industry_design",
  UIUX: "/user/design/ui-ux",

  ABOUT: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/user/profile",
  SEARCH: "/user/search",
  APTITUDE: "/user/aptitude-test",
  CAREERPATHS: "/user/career-paths",
  TIMELINE: "/user/timeline",
  DASHBOARD: "/user/dashboard",
};
export default PathConstants;
